TT#26266 Fix a390ae4b: add missing ':'
Otherwise error in trunk:
> Error: yaml: line 41: could not find expected ':'

Change-Id: I5140f083a6c635784ac895fa87e734f7dce6dc58