TT#72351 Fix 62a2332: remove symlink /usr/share/ngcp-tests -> /usr/share/ngcp-system-tests
It was a compatibility symlink, but after the log review/refactoring in
https://gerrit.mgm.sipwise.com/#/c/system-tests/+/36377/
the folder /usr/share/ngcp-system-tests is no available anymore,
so there is no point to create a broken symlink, which is spotted by Jenkins:
> https://jenkins.mgm.sipwise.com/job/check-broken-symlinks/95661/console
> ERROR: found broken symbolic links:
> /usr/share/ngcp-tests

Change-Id: Ia1307a504a3d97e68bafd3d9148c5291efcae56e