MT#61779 Remove duplicate ngcp-license-client check
There is a more complete check that should already handle the case this
instance was covering, with a non-empty license-key.

This was causing the following parse failure with the new goss version
from Debian trixie:

  ,---
  Error: could not read json data in /etc/ngcp-system-tests/510_init-daemons-ngcp.yaml: yaml: unmarshal errors:
    line 115: mapping key "ngcp-license-client.service" already defined at line 31
  `---

Reported-by: goss 0.4.9
Change-Id: I7323fbd80e2b13d0bcc280210bdb8010b910c5f1